# docker build -t beetee/vad-service:1.0.0-build -f dockerfile.dev --target build .
ARG BASE_REGISTRY="docker.io"
ARG BASE_IMAGE="python"
ARG BASE_TAG="3.11.9-bookworm"

FROM ${BASE_REGISTRY}/${BASE_IMAGE}:${BASE_TAG} as build

SHELL ["/bin/bash", "-c"]

ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8
ENV PYTHONFAULTHANDLER=1
ENV TZ=Asia/Singapore

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Keeps Python from generating .pyc files in the container
ENV PYTHONDONTWRITEBYTECODE 1

# Turns off buffering for easier container logging
ENV PYTHONUNBUFFERED 1

# Install pip requirements
COPY requirements.txt .

RUN --mount=type=cache,target=/root/.cache/pip \
    python -m venv /venv && \
    source /venv/bin/activate && \
    python -m pip install --upgrade --no-cache-dir pip && \
    pip install -r requirements.txt

ENV PATH="/venv/bin:${PATH}"

COPY ./src /src
COPY ./proto /proto

RUN python -m grpc_tools.protoc \
    -I / \
    --python_out=/src \
    --pyi_out=/src \
    --grpc_python_out=/src \
    /proto/vad.proto




